--- 
- name: "Deploying Website From Github"
  hosts: amazon
  become: true
  vars_file:
    - variable.yml
  tasks:

    - name: "Install packages"
      yum:
        name: "{{ packages }}"
        state: present

    - name: "Installing docker client for python"
      pip:
        name: docker-py
        state: present

    - name: "Restarting and enabling docker service"
      service:
        name: docker
        state: restarted
        enabled: true

    - name: "Adding ec2-user to docker"
      user:
        name: "{{ user }}"
        groups:
          - docker
        append: yes

    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"

    - name: "Adding a httpd container"
      docker_container:
        name: testcontainer
        image: "{{ image_name }}"
        recreate: true
        state: started
        ports:
          - "80:5000"

    - name: "Removing old latest image"
      when: git_status.changed
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ item }}"
        state: absent
      with_items:
        - latest
